Create workflow for publishing to private PyPI
oqc-community/qat-rpc pull request #8
Opened 2024-09-12 10:12 UTC by matt-oqc

2024-09-12 10:13 UTC, matt-oqc commented
I have read the Contributor License Agreement and I hereby accept the Terms.

2024-09-12 10:17 UTC, bgsach commented on .github/workflows/publish.yml
> +  workflow_dispatch:
I believe this triggers on any push to main OR any tag push not AND! (we have this problem on qat at the moment).

2024-09-16 14:32 UTC, keriksson-rosenqvist requested changes
I would much rather see this centralised in the https://github.com/oqc-tech/oqc-actions repo

2024-09-16 15:33 UTC, matt-oqc commented
> I would much rather see this centralised in the https://github.com/oqc-tech/oqc-actions repo

I do agree and will be happy to help get this done as part of future work.

2024-09-16 15:48 UTC, tom-oqc approved these changes

2024-09-16 16:05 UTC, bgsach approved these changes

2024-09-16 16:13 UTC, merged